// SPDX-License-Identifier: MIT
// Explicit application assets; never include runtime files or build directories.
pub static ASSETS: &[(&str, &[u8])] = &[
    ("compat/bootstrap.lock.json", include_bytes!("../compat/bootstrap.lock.json")),
    ("compat/fenix/bundle.json", include_bytes!("../compat/fenix/bundle.json")),
    ("compat/fenix/release.json", include_bytes!("../compat/fenix/release.json")),
    ("compat/graphics.lock.json", include_bytes!("../compat/graphics.lock.json")),
    ("compat/upstreams.lock.json", include_bytes!("../compat/upstreams.lock.json")),
    ("scripts/runtime/launch-msfs.sh", include_bytes!("../scripts/native-runtime/launch-msfs.sh")),
    ("scripts/runtime/play-msfs.sh", include_bytes!("../scripts/native-runtime/play-msfs.sh")),
    ("scripts/runtime/runtime-env.sh", include_bytes!("../scripts/runtime/runtime-env.sh")),
    ("scripts/runtime/xodus-service.sh", include_bytes!("../scripts/runtime/xodus-service.sh")),
    ("scripts/runtime/xodus-wine-launch", include_bytes!("../scripts/native-runtime/xodus-wine-launch")),
    ("scripts/runtime/xodus.sh", include_bytes!("../scripts/runtime/xodus.sh")),
    ("ui/app.js", include_bytes!("../ui/app.js")),
    ("ui/cloud-saves.js", include_bytes!("../ui/cloud-saves.js")),
    ("ui/fenix.js", include_bytes!("../ui/fenix.js")),
    ("ui/flight-panorama-2020.png", include_bytes!("../ui/flight-panorama-2020.png")),
    ("ui/flight-panorama.png", include_bytes!("../ui/flight-panorama.png")),
    ("ui/gsx.js", include_bytes!("../ui/gsx.js")),
    ("ui/i18n.js", include_bytes!("../ui/i18n.js")),
    ("ui/index.html", include_bytes!("../ui/index.html")),
    ("ui/launcher-updates.js", include_bytes!("../ui/launcher-updates.js")),
    ("ui/maintenance.js", include_bytes!("../ui/maintenance.js")),
    ("ui/manrope-variable.woff2", include_bytes!("../ui/manrope-variable.woff2")),
    ("ui/mark.svg", include_bytes!("../ui/mark.svg")),
    ("ui/mods.js", include_bytes!("../ui/mods.js")),
    ("ui/notices.js", include_bytes!("../ui/notices.js")),
    ("ui/problem-reports.js", include_bytes!("../ui/problem-reports.js")),
    ("ui/proton.js", include_bytes!("../ui/proton.js")),
    ("ui/setup.js", include_bytes!("../ui/setup.js")),
    ("ui/state.js", include_bytes!("../ui/state.js")),
    ("ui/store-check.js", include_bytes!("../ui/store-check.js")),
    ("ui/styles.css", include_bytes!("../ui/styles.css")),
    ("ui/updates.js", include_bytes!("../ui/updates.js")),
];
