// SPDX-License-Identifier: MIT
//! Flightdeck's Rust launcher, installer and runtime services.
pub mod api;
pub mod backend;
pub mod bootstrap;
pub mod cli;
pub mod cloud;
pub mod cloud_auto;
pub mod cloud_cache;
pub mod cloud_flow;
pub mod cloud_fs;
pub mod cloud_import;
pub mod cloud_pipe;
pub mod cloud_policy;
pub mod cloud_prefix;
pub mod cloud_process_guard;
pub mod cloud_runtime;
pub mod cloud_session;
pub mod cloud_storage;
pub mod cloud_sync;
pub mod cloud_write;
pub mod components;
pub mod desktop;
pub mod diagnostics;
pub mod display_refresh;
pub mod error;
pub mod fenix;
pub mod fenix_bundle;
pub mod fenix_diagnostics;
pub mod fenix_installer;
pub mod fenix_setup;
pub mod files;
pub mod framework;
pub mod framework_maintenance;
pub mod framework_repair;
pub mod game_install;
pub mod game_package;
pub mod game_update;
pub mod games;
pub mod graphics;
pub mod graphics_diagnostics;
pub mod graphics_settings;
pub mod gsx;
pub mod hip_probe;
mod http_client;
pub mod i18n;
pub mod inherited_fd;
pub mod installer;
pub mod integrity;
pub mod launcher_update;
pub mod loader;
pub mod log_reader;
pub mod maintenance;
pub mod mods;
pub mod native_probe;
mod neural_assets;
mod neural_decode;
pub mod neural_rendering;
pub mod neural_weights;
mod ordered_json;
pub mod owned_tree;
pub mod problem_reports;
pub mod process;
pub mod progress;
pub mod proton;
pub mod resources;
pub mod run_diagnostics;
pub mod runtime;
pub mod save_state;
pub mod server;
pub mod setup;
pub mod startup_updates;
pub mod store_check;
pub mod store_diagnostics;
mod strict_json;
pub mod supervisor;
pub mod transaction;
pub mod vr;
pub mod wine;
pub mod wine_processes;
pub mod xml;

pub use error::{Error, Result};
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
